### ISSUE TITLE
Set up PHP mailer

### ISSUE THREAD

**Issue by chadfry** [Macroscope-Software/website#10]
set this up with my email for now and I'll swap it out when we set up company email.

chadfry@me.com

**Comment by chadfry** [comment]
By this, I mean just to connect the contact form at the bottom of the page so that it works.

**Comment by chadfry** [comment]
I sent the config for sales@metascope.ca. Please update all contact buttons on website as well to this address. Thanks!

**Comment by apoorvmacroscope** [comment]
Please provide details respective to fields in attached screen.
![email_credentials](https://cloud.githubusercontent.com/assets/13028425/8546225/74fa7a32-24d3-11e5-993f-0316402cbffa.png)

**Comment by chadfry** [comment]
Ok, I'll enter it in. Have re-assigned it to myself.
