### ISSUE TITLE
Bug: nav underline

### ISSUE THREAD

**Issue by chadfry** [Macroscope-Software/website#14]
When you click on services, and then back to products in the nav menu, the underline stays on services. I think the issue is in the javascript.

**Comment by chadfry** [comment]
Make underline disappear when scrolling back to top of page

**Comment by chadfry** [comment]
Problem:
- user clicks on nav menu item and page scrolls down
- user manually scrolls to top of page
- nav menu item still shows underline
- nav menu items should have no underline when scrolled to top of page

**Comment by apoorvmacroscope** [comment]
Now underline gets removed when page is scrolled to top, please check and confirm.

**Comment by chadfry** [comment]
Thanks
