### ISSUE TITLE
Make menu disappear after selecting item on mobile

### ISSUE THREAD

**Issue by chadfry** [Macroscope-Software/website#30]

**Comment by chadfry** [comment]
problem (on mobile only)

- user touches hamburger menu icon
- menu drops down
- user selects menu item
- page scrolls to appropriate section
- menu dropdown stays open
- menu dropdown should close once user selects menu item

**Comment by apoorvmacroscope** [comment]
Now page scrolls to appropriate section and menu gets fold. Please check and confirm.

**Comment by chadfry** [comment]
works great! thanks.
