### ISSUE TITLE
Underline appears in 'Use-Case Studies' after clicking menu for a while

### ISSUE THREAD

**Issue by chadfry** [Macroscope-Software/website#39]
-user clicks a few menu items
-user scrolls down to 'use case studies' section
-user sees underline in bottom right corner
-there should be no underline there

**Comment by chadfry** [comment]
How is this going Apoorv?

**Comment by apoorvmacroscope** [comment]
I don't see this issue coming in any browser. Can you please let me know about the browser and platform which you are using?

**Comment by chadfry** [comment]
Using the latest Chrome with the latest Mac OS
<img width="1081" alt="screen shot 2015-07-20 at 5 02 40 pm" src="https://cloud.githubusercontent.com/assets/1302825/8790327/7a9cde7a-2f01-11e5-85ee-51b185b4be52.png">

Doesn't seem to happen in Safari

**Comment by apoorvmacroscope** [comment]
I checked it on my MAC, and it does not seems to be coming in any browser, neither in safari nor in chrome. I followed your mentioned steps, first clicking on some menus and then scrolling to this section, but it works fine.
