### ISSUE TITLE
test for bugs on all platforms (see pic)

### ISSUE THREAD

**Issue by chadfry** [Macroscope-Software/website#40]
![image001](https://cloud.githubusercontent.com/assets/1302825/8732151/8fb31364-2bb0-11e5-831c-dd34b1290b7d.jpg)

**Comment by chadfry** [comment]
It looks like issues with IE and firefox mainly? https://metascope.browsera.com/tests/83008-2015-07-20#page=415819

Apoorv, what are you currently using to test across platforms? And are you familiar with implementing modernizr?

**Comment by apoorvmacroscope** [comment]
can you please provide me login credentials?

**Comment by chadfry** [comment]
sure, it's just a free account:

log: cfry999@gmail.com
pass: metascope

**Comment by apoorvmacroscope** [comment]
I have made some changes (for google check), please upload them on live site.

**Comment by chadfry** [comment]
it's live now. For Google Check? What do you mean?

**Comment by apoorvmacroscope** [comment]
I mean I have done some changes recommended by google speed test, so please upload new files in order to check if update are working or not.

**Comment by chadfry** [comment]
modernizr doesn't seem to be solving the issues here: https://metascope.browsera.com/tests/83008-2015-07-20#page=415819

What do you think?
